name: "Generate web site"
description: "Generates web site from template"

runs:
  using: "composite"
  steps:
    - name: Generate web site from template
      shell: bash
      run: |
        ./packages/bodiless-cli/bin/bodiless new -r HEAD --clone-local --dest 'generated/sites/bodiless' --name 'bodiless' --site-template '__vital_next__'
        cd 'generated/sites/bodiless'
        cat package.json
        npm run setup
        cat package.json
